services:
  mysql:
    image: 'mysql:8.0.27'
    restart: 'no'
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - '../.data/mysql:/var/lib/mysql'
      - './mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf'
    environment:
      TZ: '${TZ}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_USER_PASSWORD}'

  redis:
    image: 'redis:alpine'
    restart: 'no'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    environment:
      TZ: '${TZ}'
    ports:
      - '${REDIS_PORT}:6379'

  meilisearch:
    image: 'getmeili/meilisearch:v${MEILISEARCH_VERSION}'
    restart: 'no'
    environment:
      TZ: '${TZ}'
      MEILI_MASTER_KEY: '${MEILISEARCH_PASSWORD}'
    ports:
      - '${MEILISEARCH_PORT}:7700'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'

  php:
    build: php
    restart: 'no'
    environment:
      TZ: '${TZ}'
    volumes:
      - '../backend:/var/www/backend'
      - './php/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini'
      - './php/php-fpm.dev.conf:/usr/local/etc/php-fpm.d/php-fpm.dev.conf'
      - './php/crontab:/etc/cron.d/crontab'
      - './php/horizon.conf:/etc/supervisor/conf.d/horizon.conf'
    depends_on:
      - mysql
      - redis
      - rabbitmq

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    environment:
      TZ: '${TZ}'
      PMA_HOST: '${MYSQL_HOST}'
      PMA_PORT: '${MYSQL_PORT}'
      MAX_EXECUTION_TIME: 1800
      MEMORY_LIMIT: '4G'
      UPLOAD_LIMIT: '1G'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - mysql

  nginx:
    image: 'lscr.io/linuxserver/nginx:latest'
    restart: 'no'
    cap_add:
      - 'NET_ADMIN'
    environment:
      TZ: '${TZ}'
      PUID: '1000'
      PGID: '1000'
      URL: '${NGINX_DOMAIN}'
    volumes:
      - '../backend:/var/www/backend'
      - './nginx/dev.conf:/config/nginx/site-confs/default.conf'
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    depends_on:
      - php
